
// This file has been generated by the GUI designer. Do not modify.
namespace beagleradio
{
	public partial class AnalogClock
	{
		private global::Gtk.DrawingArea drawClock;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget beagleradio.AnalogClock
			global::Stetic.BinContainer.Attach (this);
			this.Name = "beagleradio.AnalogClock";
			// Container child beagleradio.AnalogClock.Gtk.Container+ContainerChild
			this.drawClock = new global::Gtk.DrawingArea ();
			this.drawClock.Name = "drawClock";
			this.Add (this.drawClock);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.drawClock.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnDrawClockExposeEvent);
		}
	}
}
