
// This file has been generated by the GUI designer. Do not modify.
namespace beagleradio
{
	public partial class Volume
	{
		private global::Gtk.EventBox eventVolume;
		
		private global::Gtk.DrawingArea drawVolume;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget beagleradio.Volume
			global::Stetic.BinContainer.Attach (this);
			this.Name = "beagleradio.Volume";
			// Container child beagleradio.Volume.Gtk.Container+ContainerChild
			this.eventVolume = new global::Gtk.EventBox ();
			this.eventVolume.Name = "eventVolume";
			// Container child eventVolume.Gtk.Container+ContainerChild
			this.drawVolume = new global::Gtk.DrawingArea ();
			this.drawVolume.Name = "drawVolume";
			this.eventVolume.Add (this.drawVolume);
			this.Add (this.eventVolume);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.eventVolume.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnEventVolumeButtonPressEvent);
			this.eventVolume.MotionNotifyEvent += new global::Gtk.MotionNotifyEventHandler (this.OnEventVolumeMotionNotifyEvent);
			this.drawVolume.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnDrawVolumeExposeEvent);
		}
	}
}
