
// This file has been generated by the GUI designer. Do not modify.
namespace beagleradio
{
	public partial class SelectUserPass
	{
		private global::Gtk.Table table3;
		
		private global::beagleradio.KeyboardWidget keyboardwidget1;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.Table table8;
		
		private global::Gtk.Label labelTitle;
		
		private global::Gtk.Table table9;
		
		private global::Gtk.Entry entryPassword;
		
		private global::Gtk.Entry entryUser;
		
		private global::Gtk.Label labelPass;
		
		private global::Gtk.Label labelUser;
		
		private global::Gtk.VButtonBox vbuttonbox2;
		
		private global::Gtk.Button buttonPrevious;
		
		private global::Gtk.Button buttonNext1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget beagleradio.SelectUserPass
			global::Stetic.BinContainer.Attach (this);
			this.Name = "beagleradio.SelectUserPass";
			// Container child beagleradio.SelectUserPass.Gtk.Container+ContainerChild
			this.table3 = new global::Gtk.Table (((uint)(2)), ((uint)(1)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			this.table3.BorderWidth = ((uint)(4));
			// Container child table3.Gtk.Table+TableChild
			this.keyboardwidget1 = new global::beagleradio.KeyboardWidget ();
			this.keyboardwidget1.Events = ((global::Gdk.EventMask)(256));
			this.keyboardwidget1.Name = "keyboardwidget1";
			this.table3.Add (this.keyboardwidget1);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table3 [this.keyboardwidget1]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			// Container child table3.Gtk.Table+TableChild
			this.table1 = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.table8 = new global::Gtk.Table (((uint)(2)), ((uint)(1)), false);
			this.table8.Name = "table8";
			this.table8.RowSpacing = ((uint)(6));
			this.table8.ColumnSpacing = ((uint)(6));
			// Container child table8.Gtk.Table+TableChild
			this.labelTitle = new global::Gtk.Label ();
			this.labelTitle.Name = "labelTitle";
			this.labelTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Enter connection properties");
			this.table8.Add (this.labelTitle);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table8 [this.labelTitle]));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table8.Gtk.Table+TableChild
			this.table9 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table9.Name = "table9";
			this.table9.RowSpacing = ((uint)(6));
			this.table9.ColumnSpacing = ((uint)(6));
			// Container child table9.Gtk.Table+TableChild
			this.entryPassword = new global::Gtk.Entry ();
			this.entryPassword.CanFocus = true;
			this.entryPassword.Name = "entryPassword";
			this.entryPassword.Text = global::Mono.Unix.Catalog.GetString ("Electric1");
			this.entryPassword.IsEditable = true;
			this.entryPassword.InvisibleChar = '●';
			this.table9.Add (this.entryPassword);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table9 [this.entryPassword]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table9.Gtk.Table+TableChild
			this.entryUser = new global::Gtk.Entry ();
			this.entryUser.CanFocus = true;
			this.entryUser.Name = "entryUser";
			this.entryUser.Text = global::Mono.Unix.Catalog.GetString ("pgregory");
			this.entryUser.IsEditable = true;
			this.entryUser.InvisibleChar = '●';
			this.table9.Add (this.entryUser);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table9 [this.entryUser]));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table9.Gtk.Table+TableChild
			this.labelPass = new global::Gtk.Label ();
			this.labelPass.Name = "labelPass";
			this.labelPass.Xalign = 0F;
			this.labelPass.LabelProp = global::Mono.Unix.Catalog.GetString ("Pass");
			this.table9.Add (this.labelPass);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table9 [this.labelPass]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table9.Gtk.Table+TableChild
			this.labelUser = new global::Gtk.Label ();
			this.labelUser.Name = "labelUser";
			this.labelUser.Xalign = 0F;
			this.labelUser.LabelProp = global::Mono.Unix.Catalog.GetString ("User");
			this.table9.Add (this.labelUser);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table9 [this.labelUser]));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table8.Add (this.table9);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table8 [this.table9]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table1.Add (this.table8);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.table8]));
			w8.YOptions = ((global::Gtk.AttachOptions)(2));
			// Container child table1.Gtk.Table+TableChild
			this.vbuttonbox2 = new global::Gtk.VButtonBox ();
			this.vbuttonbox2.Name = "vbuttonbox2";
			this.vbuttonbox2.Spacing = 4;
			this.vbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.buttonPrevious = new global::Gtk.Button ();
			this.buttonPrevious.CanFocus = true;
			this.buttonPrevious.Name = "buttonPrevious";
			this.buttonPrevious.UseUnderline = true;
			this.buttonPrevious.Label = global::Mono.Unix.Catalog.GetString ("Previous");
			this.vbuttonbox2.Add (this.buttonPrevious);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2 [this.buttonPrevious]));
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.buttonNext1 = new global::Gtk.Button ();
			this.buttonNext1.CanFocus = true;
			this.buttonNext1.Name = "buttonNext1";
			this.buttonNext1.UseUnderline = true;
			this.buttonNext1.Label = global::Mono.Unix.Catalog.GetString ("Next");
			this.vbuttonbox2.Add (this.buttonNext1);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2 [this.buttonNext1]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.table1.Add (this.vbuttonbox2);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.vbuttonbox2]));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table3.Add (this.table1);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table3 [this.table1]));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonPrevious.Clicked += new global::System.EventHandler (this.OnButtonPreviousClicked);
			this.buttonNext1.Clicked += new global::System.EventHandler (this.OnButtonNextClicked);
			this.entryUser.FocusInEvent += new global::Gtk.FocusInEventHandler (this.OnEntryUserFocusInEvent);
			this.entryPassword.FocusInEvent += new global::Gtk.FocusInEventHandler (this.OnEntryPasswordFocusInEvent);
		}
	}
}
