
// This file has been generated by the GUI designer. Do not modify.
namespace beagleradio
{
	public partial class KeyboardWidget
	{
		private global::Gtk.Table table3;
		
		private global::Gtk.Button buttonDelete;
		
		private global::Gtk.Button buttonLetter1;
		
		private global::Gtk.Button buttonLetter10;
		
		private global::Gtk.Button buttonLetter11;
		
		private global::Gtk.Button buttonLetter12;
		
		private global::Gtk.Button buttonLetter13;
		
		private global::Gtk.Button buttonLetter14;
		
		private global::Gtk.Button buttonLetter15;
		
		private global::Gtk.Button buttonLetter16;
		
		private global::Gtk.Button buttonLetter17;
		
		private global::Gtk.Button buttonLetter18;
		
		private global::Gtk.Button buttonLetter19;
		
		private global::Gtk.Button buttonLetter2;
		
		private global::Gtk.Button buttonLetter20;
		
		private global::Gtk.Button buttonLetter21;
		
		private global::Gtk.Button buttonLetter22;
		
		private global::Gtk.Button buttonLetter23;
		
		private global::Gtk.Button buttonLetter24;
		
		private global::Gtk.Button buttonLetter25;
		
		private global::Gtk.Button buttonLetter26;
		
		private global::Gtk.Button buttonLetter27;
		
		private global::Gtk.Button buttonLetter28;
		
		private global::Gtk.Button buttonLetter29;
		
		private global::Gtk.Button buttonLetter3;
		
		private global::Gtk.Button buttonLetter30;
		
		private global::Gtk.Button buttonLetter4;
		
		private global::Gtk.Button buttonLetter5;
		
		private global::Gtk.Button buttonLetter6;
		
		private global::Gtk.Button buttonLetter7;
		
		private global::Gtk.Button buttonLetter8;
		
		private global::Gtk.Button buttonLetter9;
		
		private global::Gtk.Button buttonNext;
		
		private global::Gtk.Button buttonSet;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget beagleradio.KeyboardWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "beagleradio.KeyboardWidget";
			// Container child beagleradio.KeyboardWidget.Gtk.Container+ContainerChild
			this.table3 = new global::Gtk.Table (((uint)(3)), ((uint)(11)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(1));
			this.table3.ColumnSpacing = ((uint)(1));
			// Container child table3.Gtk.Table+TableChild
			this.buttonDelete = new global::Gtk.Button ();
			this.buttonDelete.CanFocus = true;
			this.buttonDelete.Name = "buttonDelete";
			this.buttonDelete.UseUnderline = true;
			this.buttonDelete.Label = global::Mono.Unix.Catalog.GetString ("Delete");
			this.table3.Add (this.buttonDelete);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonDelete]));
			w1.LeftAttach = ((uint)(10));
			w1.RightAttach = ((uint)(11));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter1 = new global::Gtk.Button ();
			this.buttonLetter1.CanFocus = true;
			this.buttonLetter1.Name = "buttonLetter1";
			this.buttonLetter1.UseUnderline = true;
			this.buttonLetter1.Label = global::Mono.Unix.Catalog.GetString ("Q");
			this.table3.Add (this.buttonLetter1);
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter10 = new global::Gtk.Button ();
			this.buttonLetter10.CanFocus = true;
			this.buttonLetter10.Name = "buttonLetter10";
			this.buttonLetter10.UseUnderline = true;
			this.buttonLetter10.Label = global::Mono.Unix.Catalog.GetString ("P");
			this.table3.Add (this.buttonLetter10);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter10]));
			w3.LeftAttach = ((uint)(9));
			w3.RightAttach = ((uint)(10));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter11 = new global::Gtk.Button ();
			this.buttonLetter11.CanFocus = true;
			this.buttonLetter11.Name = "buttonLetter11";
			this.buttonLetter11.UseUnderline = true;
			this.buttonLetter11.Label = global::Mono.Unix.Catalog.GetString ("A");
			this.table3.Add (this.buttonLetter11);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter11]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter12 = new global::Gtk.Button ();
			this.buttonLetter12.CanFocus = true;
			this.buttonLetter12.Name = "buttonLetter12";
			this.buttonLetter12.UseUnderline = true;
			this.buttonLetter12.Label = global::Mono.Unix.Catalog.GetString ("S");
			this.table3.Add (this.buttonLetter12);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter12]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter13 = new global::Gtk.Button ();
			this.buttonLetter13.CanFocus = true;
			this.buttonLetter13.Name = "buttonLetter13";
			this.buttonLetter13.UseUnderline = true;
			this.buttonLetter13.Label = global::Mono.Unix.Catalog.GetString ("D");
			this.table3.Add (this.buttonLetter13);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter13]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.LeftAttach = ((uint)(2));
			w6.RightAttach = ((uint)(3));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter14 = new global::Gtk.Button ();
			this.buttonLetter14.CanFocus = true;
			this.buttonLetter14.Name = "buttonLetter14";
			this.buttonLetter14.UseUnderline = true;
			this.buttonLetter14.Label = global::Mono.Unix.Catalog.GetString ("F");
			this.table3.Add (this.buttonLetter14);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter14]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.LeftAttach = ((uint)(3));
			w7.RightAttach = ((uint)(4));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter15 = new global::Gtk.Button ();
			this.buttonLetter15.CanFocus = true;
			this.buttonLetter15.Name = "buttonLetter15";
			this.buttonLetter15.UseUnderline = true;
			this.buttonLetter15.Label = global::Mono.Unix.Catalog.GetString ("G");
			this.table3.Add (this.buttonLetter15);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter15]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.LeftAttach = ((uint)(4));
			w8.RightAttach = ((uint)(5));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter16 = new global::Gtk.Button ();
			this.buttonLetter16.CanFocus = true;
			this.buttonLetter16.Name = "buttonLetter16";
			this.buttonLetter16.UseUnderline = true;
			this.buttonLetter16.Label = global::Mono.Unix.Catalog.GetString ("H");
			this.table3.Add (this.buttonLetter16);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter16]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.LeftAttach = ((uint)(5));
			w9.RightAttach = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter17 = new global::Gtk.Button ();
			this.buttonLetter17.CanFocus = true;
			this.buttonLetter17.Name = "buttonLetter17";
			this.buttonLetter17.UseUnderline = true;
			this.buttonLetter17.Label = global::Mono.Unix.Catalog.GetString ("J");
			this.table3.Add (this.buttonLetter17);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter17]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.LeftAttach = ((uint)(6));
			w10.RightAttach = ((uint)(7));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter18 = new global::Gtk.Button ();
			this.buttonLetter18.CanFocus = true;
			this.buttonLetter18.Name = "buttonLetter18";
			this.buttonLetter18.UseUnderline = true;
			this.buttonLetter18.Label = global::Mono.Unix.Catalog.GetString ("K");
			this.table3.Add (this.buttonLetter18);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter18]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.LeftAttach = ((uint)(7));
			w11.RightAttach = ((uint)(8));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter19 = new global::Gtk.Button ();
			this.buttonLetter19.CanFocus = true;
			this.buttonLetter19.Name = "buttonLetter19";
			this.buttonLetter19.UseUnderline = true;
			this.buttonLetter19.Label = global::Mono.Unix.Catalog.GetString ("L");
			this.table3.Add (this.buttonLetter19);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter19]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.LeftAttach = ((uint)(8));
			w12.RightAttach = ((uint)(9));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter2 = new global::Gtk.Button ();
			this.buttonLetter2.CanFocus = true;
			this.buttonLetter2.Name = "buttonLetter2";
			this.buttonLetter2.UseUnderline = true;
			this.buttonLetter2.Label = global::Mono.Unix.Catalog.GetString ("W");
			this.table3.Add (this.buttonLetter2);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter2]));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter20 = new global::Gtk.Button ();
			this.buttonLetter20.CanFocus = true;
			this.buttonLetter20.Name = "buttonLetter20";
			this.buttonLetter20.Label = global::Mono.Unix.Catalog.GetString ("-");
			this.table3.Add (this.buttonLetter20);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter20]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			w14.LeftAttach = ((uint)(9));
			w14.RightAttach = ((uint)(10));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter21 = new global::Gtk.Button ();
			this.buttonLetter21.CanFocus = true;
			this.buttonLetter21.Name = "buttonLetter21";
			this.buttonLetter21.UseUnderline = true;
			this.buttonLetter21.Label = global::Mono.Unix.Catalog.GetString ("Z");
			this.table3.Add (this.buttonLetter21);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter21]));
			w15.TopAttach = ((uint)(2));
			w15.BottomAttach = ((uint)(3));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter22 = new global::Gtk.Button ();
			this.buttonLetter22.CanFocus = true;
			this.buttonLetter22.Name = "buttonLetter22";
			this.buttonLetter22.UseUnderline = true;
			this.buttonLetter22.Label = global::Mono.Unix.Catalog.GetString ("X");
			this.table3.Add (this.buttonLetter22);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter22]));
			w16.TopAttach = ((uint)(2));
			w16.BottomAttach = ((uint)(3));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter23 = new global::Gtk.Button ();
			this.buttonLetter23.CanFocus = true;
			this.buttonLetter23.Name = "buttonLetter23";
			this.buttonLetter23.UseUnderline = true;
			this.buttonLetter23.Label = global::Mono.Unix.Catalog.GetString ("C");
			this.table3.Add (this.buttonLetter23);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter23]));
			w17.TopAttach = ((uint)(2));
			w17.BottomAttach = ((uint)(3));
			w17.LeftAttach = ((uint)(2));
			w17.RightAttach = ((uint)(3));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter24 = new global::Gtk.Button ();
			this.buttonLetter24.CanFocus = true;
			this.buttonLetter24.Name = "buttonLetter24";
			this.buttonLetter24.UseUnderline = true;
			this.buttonLetter24.Label = global::Mono.Unix.Catalog.GetString ("V");
			this.table3.Add (this.buttonLetter24);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter24]));
			w18.TopAttach = ((uint)(2));
			w18.BottomAttach = ((uint)(3));
			w18.LeftAttach = ((uint)(3));
			w18.RightAttach = ((uint)(4));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter25 = new global::Gtk.Button ();
			this.buttonLetter25.CanFocus = true;
			this.buttonLetter25.Name = "buttonLetter25";
			this.buttonLetter25.UseUnderline = true;
			this.buttonLetter25.Label = global::Mono.Unix.Catalog.GetString ("B");
			this.table3.Add (this.buttonLetter25);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter25]));
			w19.TopAttach = ((uint)(2));
			w19.BottomAttach = ((uint)(3));
			w19.LeftAttach = ((uint)(4));
			w19.RightAttach = ((uint)(5));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter26 = new global::Gtk.Button ();
			this.buttonLetter26.CanFocus = true;
			this.buttonLetter26.Name = "buttonLetter26";
			this.buttonLetter26.UseUnderline = true;
			this.buttonLetter26.Label = global::Mono.Unix.Catalog.GetString ("N");
			this.table3.Add (this.buttonLetter26);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter26]));
			w20.TopAttach = ((uint)(2));
			w20.BottomAttach = ((uint)(3));
			w20.LeftAttach = ((uint)(5));
			w20.RightAttach = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter27 = new global::Gtk.Button ();
			this.buttonLetter27.CanFocus = true;
			this.buttonLetter27.Name = "buttonLetter27";
			this.buttonLetter27.UseUnderline = true;
			this.buttonLetter27.Label = global::Mono.Unix.Catalog.GetString ("M");
			this.table3.Add (this.buttonLetter27);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter27]));
			w21.TopAttach = ((uint)(2));
			w21.BottomAttach = ((uint)(3));
			w21.LeftAttach = ((uint)(6));
			w21.RightAttach = ((uint)(7));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter28 = new global::Gtk.Button ();
			this.buttonLetter28.CanFocus = true;
			this.buttonLetter28.Name = "buttonLetter28";
			this.buttonLetter28.UseUnderline = true;
			this.buttonLetter28.Label = global::Mono.Unix.Catalog.GetString (",");
			this.table3.Add (this.buttonLetter28);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter28]));
			w22.TopAttach = ((uint)(2));
			w22.BottomAttach = ((uint)(3));
			w22.LeftAttach = ((uint)(7));
			w22.RightAttach = ((uint)(8));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter29 = new global::Gtk.Button ();
			this.buttonLetter29.CanFocus = true;
			this.buttonLetter29.Name = "buttonLetter29";
			this.buttonLetter29.UseUnderline = true;
			this.buttonLetter29.Label = global::Mono.Unix.Catalog.GetString (".");
			this.table3.Add (this.buttonLetter29);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter29]));
			w23.TopAttach = ((uint)(2));
			w23.BottomAttach = ((uint)(3));
			w23.LeftAttach = ((uint)(8));
			w23.RightAttach = ((uint)(9));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter3 = new global::Gtk.Button ();
			this.buttonLetter3.CanFocus = true;
			this.buttonLetter3.Name = "buttonLetter3";
			this.buttonLetter3.UseUnderline = true;
			this.buttonLetter3.Label = global::Mono.Unix.Catalog.GetString ("E");
			this.table3.Add (this.buttonLetter3);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter3]));
			w24.LeftAttach = ((uint)(2));
			w24.RightAttach = ((uint)(3));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter30 = new global::Gtk.Button ();
			this.buttonLetter30.CanFocus = true;
			this.buttonLetter30.Name = "buttonLetter30";
			this.buttonLetter30.Label = global::Mono.Unix.Catalog.GetString ("/");
			this.table3.Add (this.buttonLetter30);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter30]));
			w25.TopAttach = ((uint)(2));
			w25.BottomAttach = ((uint)(3));
			w25.LeftAttach = ((uint)(9));
			w25.RightAttach = ((uint)(10));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter4 = new global::Gtk.Button ();
			this.buttonLetter4.CanFocus = true;
			this.buttonLetter4.Name = "buttonLetter4";
			this.buttonLetter4.UseUnderline = true;
			this.buttonLetter4.Label = global::Mono.Unix.Catalog.GetString ("R");
			this.table3.Add (this.buttonLetter4);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter4]));
			w26.LeftAttach = ((uint)(3));
			w26.RightAttach = ((uint)(4));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter5 = new global::Gtk.Button ();
			this.buttonLetter5.CanFocus = true;
			this.buttonLetter5.Name = "buttonLetter5";
			this.buttonLetter5.UseUnderline = true;
			this.buttonLetter5.Label = global::Mono.Unix.Catalog.GetString ("T");
			this.table3.Add (this.buttonLetter5);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter5]));
			w27.LeftAttach = ((uint)(4));
			w27.RightAttach = ((uint)(5));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter6 = new global::Gtk.Button ();
			this.buttonLetter6.CanFocus = true;
			this.buttonLetter6.Name = "buttonLetter6";
			this.buttonLetter6.UseUnderline = true;
			this.buttonLetter6.Label = global::Mono.Unix.Catalog.GetString ("Y");
			this.table3.Add (this.buttonLetter6);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter6]));
			w28.LeftAttach = ((uint)(5));
			w28.RightAttach = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter7 = new global::Gtk.Button ();
			this.buttonLetter7.CanFocus = true;
			this.buttonLetter7.Name = "buttonLetter7";
			this.buttonLetter7.UseUnderline = true;
			this.buttonLetter7.Label = global::Mono.Unix.Catalog.GetString ("U");
			this.table3.Add (this.buttonLetter7);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter7]));
			w29.LeftAttach = ((uint)(6));
			w29.RightAttach = ((uint)(7));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter8 = new global::Gtk.Button ();
			this.buttonLetter8.CanFocus = true;
			this.buttonLetter8.Name = "buttonLetter8";
			this.buttonLetter8.UseUnderline = true;
			this.buttonLetter8.Label = global::Mono.Unix.Catalog.GetString ("I");
			this.table3.Add (this.buttonLetter8);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter8]));
			w30.LeftAttach = ((uint)(7));
			w30.RightAttach = ((uint)(8));
			// Container child table3.Gtk.Table+TableChild
			this.buttonLetter9 = new global::Gtk.Button ();
			this.buttonLetter9.CanFocus = true;
			this.buttonLetter9.Name = "buttonLetter9";
			this.buttonLetter9.UseUnderline = true;
			this.buttonLetter9.Label = global::Mono.Unix.Catalog.GetString ("O");
			this.table3.Add (this.buttonLetter9);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonLetter9]));
			w31.LeftAttach = ((uint)(8));
			w31.RightAttach = ((uint)(9));
			// Container child table3.Gtk.Table+TableChild
			this.buttonNext = new global::Gtk.Button ();
			this.buttonNext.CanFocus = true;
			this.buttonNext.Name = "buttonNext";
			this.buttonNext.UseUnderline = true;
			this.buttonNext.Label = global::Mono.Unix.Catalog.GetString ("Next");
			this.table3.Add (this.buttonNext);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonNext]));
			w32.TopAttach = ((uint)(2));
			w32.BottomAttach = ((uint)(3));
			w32.LeftAttach = ((uint)(10));
			w32.RightAttach = ((uint)(11));
			// Container child table3.Gtk.Table+TableChild
			this.buttonSet = new global::Gtk.Button ();
			this.buttonSet.CanFocus = true;
			this.buttonSet.Name = "buttonSet";
			this.buttonSet.UseUnderline = true;
			this.buttonSet.Label = global::Mono.Unix.Catalog.GetString ("Aa0#");
			this.table3.Add (this.buttonSet);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonSet]));
			w33.TopAttach = ((uint)(1));
			w33.BottomAttach = ((uint)(2));
			w33.LeftAttach = ((uint)(10));
			w33.RightAttach = ((uint)(11));
			this.Add (this.table3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonSet.Clicked += new global::System.EventHandler (this.OnSetShiftPressed);
			this.buttonNext.Clicked += new global::System.EventHandler (this.OnNextPressed);
			this.buttonLetter9.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter8.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter7.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter6.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter5.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter4.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter30.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter3.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter29.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter28.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter27.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter26.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter25.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter24.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter23.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter22.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter21.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter20.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter2.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter19.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter18.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter17.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter16.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter15.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter14.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter13.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter12.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter11.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter10.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonLetter1.Clicked += new global::System.EventHandler (this.CharacterPressed);
			this.buttonDelete.Pressed += new global::System.EventHandler (this.OnButtonDeletePressed);
		}
	}
}
