
// This file has been generated by the GUI designer. Do not modify.
namespace beagleradio
{
	public partial class WeatherView
	{
		private global::Gtk.Table table13;
		
		private global::Gtk.DrawingArea drawWeather;
		
		private global::Gtk.Table tableWeather;
		
		private global::Gtk.EventBox eventDay1;
		
		private global::Gtk.Image imageDay1;
		
		private global::Gtk.EventBox eventDay2;
		
		private global::Gtk.Image imageDay2;
		
		private global::Gtk.EventBox eventDay3;
		
		private global::Gtk.Image imageDay3;
		
		private global::Gtk.EventBox eventDay4;
		
		private global::Gtk.Image imageDay4;
		
		private global::Gtk.EventBox eventMorning1;
		
		private global::Gtk.Image imageMorning1;
		
		private global::Gtk.EventBox eventMorning2;
		
		private global::Gtk.Image imageMorning2;
		
		private global::Gtk.EventBox eventMorning3;
		
		private global::Gtk.Image imageMorning3;
		
		private global::Gtk.EventBox eventMorning4;
		
		private global::Gtk.Image imageMorning4;
		
		private global::Gtk.Label labelDay1;
		
		private global::Gtk.Label labelDay2;
		
		private global::Gtk.Label labelDay3;
		
		private global::Gtk.Label labelDay4;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget beagleradio.WeatherView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "beagleradio.WeatherView";
			// Container child beagleradio.WeatherView.Gtk.Container+ContainerChild
			this.table13 = new global::Gtk.Table (((uint)(2)), ((uint)(1)), false);
			this.table13.Name = "table13";
			this.table13.RowSpacing = ((uint)(6));
			this.table13.ColumnSpacing = ((uint)(6));
			// Container child table13.Gtk.Table+TableChild
			this.drawWeather = new global::Gtk.DrawingArea ();
			this.drawWeather.Name = "drawWeather";
			this.table13.Add (this.drawWeather);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table13 [this.drawWeather]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			// Container child table13.Gtk.Table+TableChild
			this.tableWeather = new global::Gtk.Table (((uint)(3)), ((uint)(4)), false);
			this.tableWeather.Name = "tableWeather";
			this.tableWeather.RowSpacing = ((uint)(6));
			this.tableWeather.ColumnSpacing = ((uint)(6));
			// Container child tableWeather.Gtk.Table+TableChild
			this.eventDay1 = new global::Gtk.EventBox ();
			this.eventDay1.Name = "eventDay1";
			this.eventDay1.VisibleWindow = false;
			// Container child eventDay1.Gtk.Container+ContainerChild
			this.imageDay1 = new global::Gtk.Image ();
			this.imageDay1.HeightRequest = 48;
			this.imageDay1.Name = "imageDay1";
			this.eventDay1.Add (this.imageDay1);
			this.tableWeather.Add (this.eventDay1);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tableWeather [this.eventDay1]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableWeather.Gtk.Table+TableChild
			this.eventDay2 = new global::Gtk.EventBox ();
			this.eventDay2.Name = "eventDay2";
			this.eventDay2.VisibleWindow = false;
			// Container child eventDay2.Gtk.Container+ContainerChild
			this.imageDay2 = new global::Gtk.Image ();
			this.imageDay2.HeightRequest = 48;
			this.imageDay2.Name = "imageDay2";
			this.eventDay2.Add (this.imageDay2);
			this.tableWeather.Add (this.eventDay2);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.tableWeather [this.eventDay2]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableWeather.Gtk.Table+TableChild
			this.eventDay3 = new global::Gtk.EventBox ();
			this.eventDay3.Name = "eventDay3";
			this.eventDay3.VisibleWindow = false;
			// Container child eventDay3.Gtk.Container+ContainerChild
			this.imageDay3 = new global::Gtk.Image ();
			this.imageDay3.HeightRequest = 48;
			this.imageDay3.Name = "imageDay3";
			this.eventDay3.Add (this.imageDay3);
			this.tableWeather.Add (this.eventDay3);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.tableWeather [this.eventDay3]));
			w7.TopAttach = ((uint)(2));
			w7.BottomAttach = ((uint)(3));
			w7.LeftAttach = ((uint)(2));
			w7.RightAttach = ((uint)(3));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableWeather.Gtk.Table+TableChild
			this.eventDay4 = new global::Gtk.EventBox ();
			this.eventDay4.Name = "eventDay4";
			this.eventDay4.VisibleWindow = false;
			// Container child eventDay4.Gtk.Container+ContainerChild
			this.imageDay4 = new global::Gtk.Image ();
			this.imageDay4.HeightRequest = 0;
			this.imageDay4.Name = "imageDay4";
			this.eventDay4.Add (this.imageDay4);
			this.tableWeather.Add (this.eventDay4);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tableWeather [this.eventDay4]));
			w9.TopAttach = ((uint)(2));
			w9.BottomAttach = ((uint)(3));
			w9.LeftAttach = ((uint)(3));
			w9.RightAttach = ((uint)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableWeather.Gtk.Table+TableChild
			this.eventMorning1 = new global::Gtk.EventBox ();
			this.eventMorning1.Name = "eventMorning1";
			this.eventMorning1.VisibleWindow = false;
			// Container child eventMorning1.Gtk.Container+ContainerChild
			this.imageMorning1 = new global::Gtk.Image ();
			this.imageMorning1.HeightRequest = 48;
			this.imageMorning1.Name = "imageMorning1";
			this.eventMorning1.Add (this.imageMorning1);
			this.tableWeather.Add (this.eventMorning1);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.tableWeather [this.eventMorning1]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableWeather.Gtk.Table+TableChild
			this.eventMorning2 = new global::Gtk.EventBox ();
			this.eventMorning2.Name = "eventMorning2";
			this.eventMorning2.VisibleWindow = false;
			// Container child eventMorning2.Gtk.Container+ContainerChild
			this.imageMorning2 = new global::Gtk.Image ();
			this.imageMorning2.HeightRequest = 48;
			this.imageMorning2.Name = "imageMorning2";
			this.eventMorning2.Add (this.imageMorning2);
			this.tableWeather.Add (this.eventMorning2);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tableWeather [this.eventMorning2]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableWeather.Gtk.Table+TableChild
			this.eventMorning3 = new global::Gtk.EventBox ();
			this.eventMorning3.Name = "eventMorning3";
			this.eventMorning3.VisibleWindow = false;
			// Container child eventMorning3.Gtk.Container+ContainerChild
			this.imageMorning3 = new global::Gtk.Image ();
			this.imageMorning3.HeightRequest = 48;
			this.imageMorning3.Name = "imageMorning3";
			this.eventMorning3.Add (this.imageMorning3);
			this.tableWeather.Add (this.eventMorning3);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.tableWeather [this.eventMorning3]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.LeftAttach = ((uint)(2));
			w15.RightAttach = ((uint)(3));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableWeather.Gtk.Table+TableChild
			this.eventMorning4 = new global::Gtk.EventBox ();
			this.eventMorning4.Name = "eventMorning4";
			this.eventMorning4.VisibleWindow = false;
			// Container child eventMorning4.Gtk.Container+ContainerChild
			this.imageMorning4 = new global::Gtk.Image ();
			this.imageMorning4.HeightRequest = 48;
			this.imageMorning4.Name = "imageMorning4";
			this.eventMorning4.Add (this.imageMorning4);
			this.tableWeather.Add (this.eventMorning4);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.tableWeather [this.eventMorning4]));
			w17.TopAttach = ((uint)(1));
			w17.BottomAttach = ((uint)(2));
			w17.LeftAttach = ((uint)(3));
			w17.RightAttach = ((uint)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableWeather.Gtk.Table+TableChild
			this.labelDay1 = new global::Gtk.Label ();
			this.labelDay1.Name = "labelDay1";
			this.labelDay1.LabelProp = global::Mono.Unix.Catalog.GetString ("Loading");
			this.tableWeather.Add (this.labelDay1);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.tableWeather [this.labelDay1]));
			w18.XOptions = ((global::Gtk.AttachOptions)(7));
			w18.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child tableWeather.Gtk.Table+TableChild
			this.labelDay2 = new global::Gtk.Label ();
			this.labelDay2.Name = "labelDay2";
			this.labelDay2.LabelProp = global::Mono.Unix.Catalog.GetString ("Loading");
			this.tableWeather.Add (this.labelDay2);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.tableWeather [this.labelDay2]));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(7));
			w19.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child tableWeather.Gtk.Table+TableChild
			this.labelDay3 = new global::Gtk.Label ();
			this.labelDay3.Name = "labelDay3";
			this.labelDay3.LabelProp = global::Mono.Unix.Catalog.GetString ("Loading");
			this.tableWeather.Add (this.labelDay3);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.tableWeather [this.labelDay3]));
			w20.LeftAttach = ((uint)(2));
			w20.RightAttach = ((uint)(3));
			w20.XOptions = ((global::Gtk.AttachOptions)(7));
			w20.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child tableWeather.Gtk.Table+TableChild
			this.labelDay4 = new global::Gtk.Label ();
			this.labelDay4.Name = "labelDay4";
			this.labelDay4.LabelProp = global::Mono.Unix.Catalog.GetString ("Loading");
			this.tableWeather.Add (this.labelDay4);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.tableWeather [this.labelDay4]));
			w21.LeftAttach = ((uint)(3));
			w21.RightAttach = ((uint)(4));
			w21.XOptions = ((global::Gtk.AttachOptions)(7));
			w21.YOptions = ((global::Gtk.AttachOptions)(0));
			this.table13.Add (this.tableWeather);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table13 [this.tableWeather]));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table13);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.tableWeather.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnTableWeatherExposeEvent);
			this.eventMorning4.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnEventMorning4ButtonPressEvent);
			this.eventMorning3.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnEventMorning3ButtonPressEvent);
			this.eventMorning2.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnEventMorning2ButtonPressEvent);
			this.eventMorning1.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnEventMorning1ButtonPressEvent);
			this.eventDay4.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnEventDay4ButtonPressEvent);
			this.eventDay3.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnEventDay3ButtonPressEvent);
			this.eventDay2.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnEventDay2ButtonPressEvent);
			this.eventDay1.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnEventDay1ButtonPressEvent);
			this.drawWeather.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnDrawWeatherExposeEvent);
		}
	}
}
